--WHENEVER SQLERROR EXIT SQL.SQLCODE;
-- set echo on;
set verify off;
/* Create DB */
CREATE PLUGGABLE DATABASE datamart
ADMIN USER sysdm IDENTIFIED BY oracle
FILE_NAME_CONVERT = ('&DATA_PATH/', '&DATA_PATH/DATAMART/');

ALTER PLUGGABLE DATABASE datamart OPEN;

-- Setup datamart root...
ALTER SESSION SET CONTAINER = datamart;
-- CREATE USER sysdm IDENTIFIED BY oracle;
GRANT dba TO sysdm;

/* Tablespaces */
-- Creating tablespaces...
CONNECT &ADMIN_NAME/&ADMIN_PASS@&DB_TNS_PDB;
ALTER SESSION SET CONTAINER = datamart;

CREATE SMALLFILE TABLESPACE tbs_devdata 
DATAFILE '&DATA_PATH/DATAMART/tbs_devdata01.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 1G;

CREATE SMALLFILE TABLESPACE tbs_datamart 
DATAFILE '&DATA_PATH/DATAMART/tbs_datamart01.dbf' 
SIZE 2G AUTOEXTEND ON NEXT 500M MAXSIZE 12G;

CREATE SMALLFILE TABLESPACE tbs_datamart_idx 
DATAFILE '&DATA_PATH/DATAMART/tbs_datamart_idx01.dbf' 
SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 10G;

/* Create cdb admin */
CREATE USER dm_nfzhosp
IDENTIFIED BY oracle
DEFAULT TABLESPACE tbs_datamart
QUOTA 12G ON tbs_datamart;

