CREATE ROLE dataengineer;
GRANT USAGE, CREATE ON SCHEMA hospital TO dataengineer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hospital TO dataengineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA hospital
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dataengineer;